global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['ssh-tunnel:9113']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['ssh-tunnel:9100'] 
